### ISSUE TITLE
21. 浏览器支持与回退机制

### ISSUE THREAD

**Issue by jobn123** [jobn123/blog#21]
## 浏览器兼容性的网站

* Can I Use... (http://caniuse.com)
* WebPlatform.org (http://webplatform.org)
* Mozilla Develop Network (http://developer.mozilla.org)

## 如果有的特性已经得到浏览器的支持了，但是不同的浏览器表现有些细微的差别`标准语法要写在最后`，例如

```css
background-image: -webkit-linear-gradient(top, hsl(0, 80%, 70%), #bada55); /* For Chrome 25 and Safari 6, iOS 6.1, Android 4.3 */
background-image:    -moz-linear-gradient(top, hsl(0, 80%, 70%), #bada55); /* For Firefox (3.6 to 15) */
background-image:      -o-linear-gradient(top, hsl(0, 80%, 70%), #bada55); /* For old Opera (11.1 to 12.0) */
background-image:         linear-gradient(to bottom, hsl(0, 80%, 70%), #bada55); /* Standard syntax; must be last */
```

## 通常为了兼容有些低版本的浏览器，我们要做些版本回退机制，不至于使网站挂掉，例如当我们指定一个渐变色作为背景的时候，最好在前面加一行实色背景的声明

```css
   background: rgb(255, 128, 0);
   background: -moz-linear-gradient(0deg, yellow, red);
   background: -o-linear-gradient(0deg, yellow, red);
   background: -webkit-linear-gradient(0deg, yellow, red);
   background: linear-gradient(0deg, yellow, red);
```

我们还可以的借助[Modernizr](http://modernizr.com/) 这样的工具给根元素体检一些辅助类，比如`text-shadow`或`no-textshadow` ，这样可以针对支持或者不支持某些特性的浏览器分别编写样式，就像这样

```css
  h1 {color: : red}

  .textshadow h1 {
    color: transparent;
    text-shadow: 0 0.3em gray;
  }
```
如果你想尝试使用的某个css特性非常新，还可以试试`@supports` 规则来实现回退，上面的代码用`@supports`可以这样写
```css
 h1 { color: gray }
 @supports (text-shadow: 0 0.3em gray) {
   h1 {
     color: transparent;
     text-shadow: 0 0.3em gray
   }
 }
```

但是目前还是要慎用`@supports`,上面的例子中的投影效果只会在支持`text-shadow`并且支持`@supports`规则的浏览器中生效

如果你不打算使用`Modernizr` 这样的库，也可以自己写一小段js代码，实现相同的相同的功能

```javascript
var root = document.documentElement; //html

if('text-shadow' in roor.style) {
  root.classList.add('text-shadow')
} else {
  root.classList.add('no-textshadow')
}
```
可以稍微修改下，抽成一个函数检测多个属性

```javascript
  function testProperty(property) {
    var root = document.documentElement;
    if(property in root.style) {
      root.classList.add(property.toLowerCase());
      return true;
    }
    root.classList.add('no-' + property.toLowerCase());
    return false;
  }
```
我们还可以检测某个具体的值是否支持

```javascript
 function testvalue(id, value, property) {
   var dummy = document.createElement('p');
   dummy.style[property] = value;

   if(dummy.style[property]) {
     root.classList.add(id);
     return true
   }

   root.classList.add('no-'id);
   return false
 }
```
