### ISSUE TITLE
23. 移动端开发总结

### ISSUE THREAD

**Issue by jobn123** [jobn123/blog#23]
## 设置元素水平垂直居中
```css
 display : -webkit-box;
 -webkit-box-orient : horizontal;
 -webkit-box-pack : center;
 -webkit-box-align : center;
 display : -moz-box;
 -moz-box-orient : horizontal;
 -moz-box-pack : center;
 -moz-box-align : center;
```
## input 在ios中 focus() 无效
可能是 `user-select: none` 导致的，默认的`user-select:text` 就可以

## 消除display: inline-block 之间的间隙

父元素设置 `font-size:0`

## iOS input 默认顶部有内阴影

```css
input[type="text"] {
  -webkit-appearance: none;
}
```
