### ISSUE TITLE
css 滚动的同时隐藏滚动条

### ISSUE THREAD

**Issue by jobn123** [jobn123/blog#38]
```css
nav {
  width: 12rem;
  height: 50px;
  line-height: 50px;
  font-size: 0;
  margin: 0 auto;
  white-space: nowrap;
  overflow-x: scroll;
}
nav::-webkit-scrollbar {
  display: none;
}
```

[参考](https://blog.niceue.com/front-end-development/hide-scrollbar-but-still-scrollable-using-css.html)
